#!/usr/bin/env bash
# A script that that transfers a file from our client to a server.
# Accepts 4 parameters
# The path to the file to be transferred ($1)
# The IP of the server we want to transfer the file to ($4)
# The username scp connects with ($3)
# The path to the SSH private key that scp uses ($4)
# scp must transfer the file to the user home directory ~/
#Strict host key checking must be disabled when using scp

# Check if less than 3 parameters are provided
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

if [ "$#" -lt 4 ];
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
