#!/usr/bin/env bash
# Install Ngnix to web server wb01
# Nginx should be listening on port 80
# Updating package list and installing Nginx
sudo apt-get update -y
sudo apt-get -y install nginx

# Configuring Ngnix to listen to port 80
sudo ufw allow 'Nginx HTTP'
# Creating a simple html page with "Hello, world!" message
sudo echo "Hello, world!" | sudo tee /var/www/html/index.html
# starting Nginx
sudo service nginx start
