#!/bin/env bash
# Configuring Nginx server for 301 permanent redirect
# Define the redirect configuration
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

REDIRECT_CONFIG="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com permanent;"

# Nginx configuration file path (adjust as needed)
NGINX_CONF_FILE="/etc/nginx/sites-enabled/default"

# Use sed to perform the replacement
sudo sed -i "s/server_name _;/$REDIRECT_CONFIG/" "$NGINX_CONF_FILE"

# Reload nginx
sudo service nginx restart
