#!/usr/bin/env bash
# Configuring nginx server to have a 301 permament Redirect page

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

# setting the default Index Page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirecting a specific endpoint
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;/" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
