#!/usr/bin/env bash
# A script containing commands to automatically configure a Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.digitalocean.com/ permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
