#!/usr/bin/env bash
# Configuring nginx server to have a custom 404 page 
# containing the string

sudo apt-get update
sudo apt-get install -y nginx

# Setting the default Index page
# echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirecting to a specific endpoint
# sudo sed -i '/server_name _;/c server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com permanent;' /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com permanent;\n\terror_page 404 \/404.html;\n\tlocation \/404.html{\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
