#!/usr/bin/env bash
# A script that installs and configures HAProxy on lb-01 server

# Update and upgrade the package list
sudo apt-get update && sudo apt-get upgrade -y

# Install HAProxy
# sudo add-apt-repository ppa:vbernat/haproxy -y
sudo apt-get install haproxy
# sudo apt update
# sudo apt install --no-install-recommends haproxy

# HAProxy Configuration
load_balancer_config="\
frontend haproxy_balancer
        bind *:80
        mode http
        default_backend webserver_backend
backend webserver_backend
        balance roundrobin
        server 324857-web-01 34.234.203.177:80 check
        server 324857-web-02 52.72.75.78:80 check
"
echo "$load_balancer_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Grant necessary Permissions
# sudo chmod o+r /etc/haproxy/haproxy.cfg

# Enable HAProxy (adjust for your distribution)
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart
