#!/usr/bin/env bash
# set up load balancer
balancer_config="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 324857-web-01 18.215.160.180:80 check
    server 324857-web-02 3.95.32.201:80 check
"
# Update packages
sudo apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy

echo "$balancer_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable Haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAProxy config file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
service haproxy restart
