#!/usr/bin/env bash
# A script that installs and configures HAProxy on lb-01 server

# Update and upgrade the package list
apt-get update && apt-get upgrade -y

# Install HAProxy
apt-get install -y haproxy

# Edit Haproxy config file
cp -a /etc/haproxy/haproxy.cfg{,.original_copy}

load_balancer_config="
                    frontend haproxy_balancer
                            bind *:80
                            mode http
                            default_backend webserver_backend

                    backend webserver_backend
		                    mode http
                            balance roundrobin
                            server 324857-web-01 34.234.203.177:80 check
                            server 324857-web-02 52.72.75.78:80 check
                      "
echo "$load_balancer_config" > /etc/haproxy/haproxy.cfg

# Enable HAProxy
echo "ENABLED=1" > /etc/default/haproxy

# Restart HAProxy service
sudo service restart haproxy
