#!/usr/bin/env bash
# Solving the problem of server not listening to port 80
# Delete the current current sites-available/default file and replacing it with its copy that's OK
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
